name: CI/CD Pipeline - Sync DEV Files to Production

on:
  push:
    branches:
      - main  # Runs when dev changes are merged into main

jobs:
  sync_to_production:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Detect changed files with `_dev`
      id: changes
      run: |
        echo "Changed files with _dev:"
        
        # Fetch history to ensure HEAD^ works
        git fetch --prune --unshallow || true
        
        # Get changed files that contain `_dev`
        if git rev-parse HEAD^ >/dev/null 2>&1; then
          git diff --name-only HEAD^ HEAD | grep '_dev' | tee changed_files.txt || true
        else
          echo "No previous commit, skipping diff check." > changed_files.txt
        fi

        # Export each changed file as an environment variable
        while read file; do
          echo "${file}_changed=true" >> $GITHUB_ENV
        done < changed_files.txt

    - name: Clone production repository
      env:
        PROD_REPO: "https://github.com/nikolaslyonsLW/LW-Prod-Lambdas.git"
        GITHUB_TOKEN: ${{ secrets.TOKEN_PROD }}
      run: |
        git clone https://x-access-token:${{ secrets.TOKEN_PROD }}@github.com/nikolaslyonsLW/LW-Prod-Lambdas.git production-repo
        cd production-repo
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        cd ..

    - name: Sync `_dev` files to production and remove `_dev`
      run: |
        while read file; do
          if [ "$(printenv ${file}_changed)" == "true" ]; then
            echo "Syncing $file to production repo..."

            # Remove _dev from filename
            new_file=$(echo $file | sed 's/_dev//')

            # Copy file with new name to production repository
            cp "$file" "production-repo/$new_file"

            cd production-repo

            # Commit and push the file
            git add "$new_file"
            git commit -m "Auto-sync $file as $new_file from main repo"
            git push origin main

            cd ..
          fi
        done < changed_files.txt
